name: Python Package on LSST Stack

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  HOME: /home/lsst

jobs:
  build:

    runs-on: ubuntu-latest
    container: lsstsqre/centos:7-stack-lsst_distrib-v19_0_0

    steps:
    - name: Install git
      run: |
        cd $HOME
        source /opt/lsst/software/stack/loadLSST.bash
        setup lsst_distrib
        conda install -y git
    - name: Check out code
      run: |
        cd $HOME
        source /opt/lsst/software/stack/loadLSST.bash
        setup lsst_distrib
        git clone https://github.com/${GITHUB_REPOSITORY}
        cd supreme
        git fetch origin ${GITHUB_REF}:TESTING
        git checkout TESTING
    - name: Install dependencies
      run: |
        cd $HOME/supreme
        source /opt/lsst/software/stack/loadLSST.bash
        setup lsst_distrib
        pip install -r requirements.txt
        pip install .[full]
    - name: Lint with flake8
      run: |
        cd $HOME/supreme
        source /opt/lsst/software/stack/loadLSST.bash
        setup lsst_distrib
        # stop the build if it fails flake8 with default setup.cfg
        flake8 . --count --show-source --statistics
    - name: Test with pytest
      run: |
        cd $HOME/supreme
        source /opt/lsst/software/stack/loadLSST.bash
        setup lsst_distrib
        pytest
