name: Python Package on LSST Stack

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  HOME: /home/lsst

jobs:
  build:

    runs-on: ubuntu-latest
    container: lsstsqre/centos:7-stack-lsst_distrib-v19_0_0

    steps:
    - name: Setup Environment
      run: |
        cd $HOME
        echo "source /opt/lsst/software/stack/loadLSST.bash" >> .bashrc
        echo "setup lsst_distrib" >> .bashrc
        echo "cd $HOME" >> $HOME/.bashrc
    - name: Install git
      shell: bash -l {0}
      run: |
        conda install -y git
    - name: Check out test data
      shell: bash -l {0}
      run: |
        git clone https://github.com/LSSTDESC/supreme_testdata
        cd supreme_testdata
        echo "setup -j -r ${PWD}" >> $HOME/.bashrc
    - name: Check out code
      shell: bash -l {0}
      run: |
        git clone https://github.com/${GITHUB_REPOSITORY}
        cd supreme
        git fetch origin ${GITHUB_REF}:TESTING
        git checkout TESTING
        echo "cd ${PWD}" >> $HOME/.bashrc
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        pip install -r requirements.txt
        pip install .[full]
    - name: Lint with flake8
      shell: bash -l {0}
      run: |
        # stop the build if it fails flake8 with default setup.cfg
        flake8 . --count --show-source --statistics
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pytest
